### PR TITLE
Update for V1.0.0

### PR DESCRIPTION
**Pull request by katosdev**
## Update to Flarum V1.0.0

**Changes proposed in this pull request:**
Updates extension to support Flarum V1.0.0

### CODE REVIEW

**Review by davwheat — APPROVED** [review]
Just need an `npm i` to save the package.json changes. :)

**Comment by katosdev** [comment]
> Just need an `npm i` to save the package.json changes. :)

I did ? :-)

**Comment by davwheat** [comment]
Weird... the lockfile doesn't seem to have changed. Lemme try it locally.

**Review by davwheat — APPROVED** [review]

**Comment by katosdev** [comment]
> Weird... the lockfile doesn't seem to have changed. Lemme try it locally.

How bizarre! Good spot, thanks @davwheat

**Pull request merged**
